FROM python:3.11.5 as builder

WORKDIR /wombo_clicker

RUN useradd -m builduser && chown -R builduser:builduser .
USER builduser

COPY requirements.txt .

RUN pip install --user --upgrade pip --no-cache-dir && \
    pip install  --user -r requirements.txt --no-cache-dir



FROM python:3.11.5-slim-bullseye

COPY . /wombo_clicker
COPY --from=builder /home/builduser/.local /home/clicker/.local

RUN apt-get update && apt-get install -y wget unzip && \
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt install -y ./google-chrome-stable_current_amd64.deb && \
    rm google-chrome-stable_current_amd64.deb && \
    apt-get clean && \
    useradd -m clicker && chown -R clicker:clicker /wombo_clicker && \
    chown -R clicker:clicker /home/clicker

ENV PATH=/home/clicker/.local:$PATH

WORKDIR /wombo_clicker/scripts

USER clicker

ENTRYPOINT ["python3", "main.py"]