
services:
  frontend:
    build: 
      context: ./example-frontend
      dockerfile: Dockerfile_frontend
    ports:
      - 5000:5000

  backend:
    build: 
      context: ./example-backend
      dockerfile: Dockerfile_backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testtest
      - POSTGRES_DATABASE=postgres

  redis:
    image: redis
    restart: unless-stopped

  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=testtest
    volumes:
      - ./volumes/database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

  web:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"

  
